Correcion de errores de archivos js
Patagonian-IUPA/codigo-prolijo pull request #4
Opened 2020-12-14 13:43 UTC by Arcaytus

Hola Eduardo, subo las correciones que hice a los archivos class.js y file.js

2020-12-14 19:42 UTC, reduardo7 requested changes

2020-12-14 19:42 UTC, reduardo7 commented on class.js
> +    console.info (`Color: ${this.color}. Peso: ${this.peso}`);
```suggestion
    console.info(`Color: ${this.color}. Peso: ${this.peso}`);
```

2020-12-14 19:42 UTC, reduardo7 commented on class.js
> +      console.info ('Imprimir!');
```suggestion
      console.info('Imprimir!');
```

2020-12-14 19:42 UTC, reduardo7 commented on file.js
> +    const id = prompt ('ID a leer:');
```suggestion
    const id = prompt('ID a leer:');
```

2020-12-14 19:42 UTC, reduardo7 commented on file.js
> +    const data = db.read (id);
```suggestion
    const data = db.read(id);
```

2020-12-14 19:42 UTC, reduardo7 commented on file.js
> +    alert (`Error- Vuelva a  ingresar el ID a leer!\n\n\t ${err.message}`);
```suggestion
    alert(`Error- Vuelva a  ingresar el ID a leer!\n\n\t ${err.message}`);
```

2020-12-14 19:42 UTC, reduardo7 commented on file.js
> +    console.warn ('Error- Vuelva a  ingresar el ID a leer', err);
```suggestion
    console.warn('Error- Vuelva a  ingresar el ID a leer', err);
```

2020-12-14 19:42 UTC, reduardo7 commented on file.js
> +    console.info ('Resultado:', data);
```suggestion
    console.info('Resultado:', data);
```

2020-12-14 19:42 UTC, reduardo7 commented on file.js
> +    console.warn ('Error al leer desde DB', err);
```suggestion
    alert('Error al leer desde DB');
    alert(`Error al leer desde DB\n\n\t ${err.message}`);
    console.warn('Error al leer desde DB', err);
```

2020-12-14 19:42 UTC, reduardo7 commented on file.js
> +    console.warn ('Error al conectar', err);
```suggestion
    alert('Error al conectar');
    alert(`Error al conectar\n\n\t ${err.message}`);
    console.warn('Error al conectar', err);
```

2020-12-14 19:42 UTC, reduardo7 commented on file.js
> +    const dato = prompt ('Nuevo Dato:');
```suggestion
    const id = prompt('Nuevo ID:');
    const dato = prompt('Nuevo Dato:');
```

2020-12-14 19:42 UTC, reduardo7 commented on file.js
> +   console.warn ('Error al cargar', err);
```suggestion
   alert(`Error al cargar! \n \n \t ${err.message}`);
   console.warn('Error al cargar', err);
```

2020-12-14 19:42 UTC, reduardo7 commented on file.js
> +    console.warn ('Error al Desconectar', err);
```suggestion
    alert(`Error al Desconectar \n \n \t ${err.message}`);
    console.warn('Error al Desconectar', err);
```

2020-12-14 20:14 UTC, Arcaytus commented
Suggestions added

2020-12-15 15:53 UTC, reduardo7 approved these changes

2020-12-15 15:54 UTC, reduardo7 commented
Buen trabajo! 👍

2020-12-15 15:54 UTC, closed without merging