Modifico los archivos js para hacer el código más legible
Patagonian-IUPA/codigo-prolijo pull request #6
Opened 2021-02-11 00:35 UTC by aldocape

Práctica de código prolijo

2021-02-11 12:40 UTC, reduardo7 requested changes

2021-02-11 12:40 UTC, reduardo7 commented on class.js
> +  */
Este bloque se encuentra dentro del método `ver()`.
```suggestion
    /*
    // Prueba
    test() {
      console.info('Test');
    }
    */
```

2021-02-11 12:40 UTC, reduardo7 commented on file.js
> +    console.warn('Error al Desconectar',err);
Dejar un espacio luego de cada `,`.
```suggestion
    console.warn('Error al Desconectar', err);
```

2021-02-11 12:40 UTC, reduardo7 commented on file.js
> +    console.warn('Error al Desconectar',err);
Nota: Aplicar en todos los puntos que corresponda.

2021-02-11 12:40 UTC, reduardo7 commented on file.js
> +    //se vuelve a habilitar el boton
Dejar un espacio luego de abrir el comentario `//`.
```suggestion
    // se vuelve a habilitar el boton
```

2021-02-11 22:44 UTC, aldocape commented on file.js
> +    //se vuelve a habilitar el boton
Listo Edu!! Ya cambié lo que me indicaste, muchas gracias!!

2021-02-12 14:59 UTC, reduardo7 approved these changes

2021-02-12 15:00 UTC, reduardo7 commented
Perfecto!

2021-02-12 15:00 UTC, closed without merging